services:
  - type: web
    name: intake-prototype-backend
    env: python
    plan: starter
    pythonVersion: "3.11"  
    buildCommand: |
      apt-get update
      apt-get install -y poppler-utils
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY  
        sync: false
      - key: AWS_REGION
        value: us-east-1

databases:
  - name: intake-db
    plan: free
    databaseName: intake
    user: intake_user